# Copyright (C) 2003-2008 Avery J. Regier.
#
# This file is part of the Tournament Pool and Bracket Tracker.
#
# Tournament Pool and Bracket Tracker is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
# 
# Tournament Pool and Bracket Tracker is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

USE TOURNAMENT;

SELECT @tournament_type_id:=TOURNAMENT_TYPE_ID FROM TOURNAMENT_TYPE WHERE NAME='NCAA Tournament';
SELECT @min_seed_id:=MIN(SEED_ID)-1 FROM SEED WHERE TOURNAMENT_TYPE_ID=@tournament_type_id;

INSERT INTO TOURNAMENT (NAME, TOURNAMENT_TYPE_ID)
VALUES ('2005 Women\s NCAA Tournament', @tournament_type_id);

SELECT @tournament_id:=MAX(TOURNAMENT_ID) FROM TOURNAMENT;

INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 201, @min_seed_id+1);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 202, @min_seed_id+2);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 203, @min_seed_id+3);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 204, @min_seed_id+4);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 205, @min_seed_id+5);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 206, @min_seed_id+6);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 207, @min_seed_id+7);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 208, @min_seed_id+8);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 209, @min_seed_id+9);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 210, @min_seed_id+10);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 211, @min_seed_id+11);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 212, @min_seed_id+12);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 213, @min_seed_id+13);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 214, @min_seed_id+14);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 215, @min_seed_id+15);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 216, @min_seed_id+16);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 217, @min_seed_id+17);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 218, @min_seed_id+18);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 219, @min_seed_id+19);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 220, @min_seed_id+20);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 221, @min_seed_id+21);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 222, @min_seed_id+22);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 223, @min_seed_id+23);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 224, @min_seed_id+24);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 225, @min_seed_id+25);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 226, @min_seed_id+26);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 227, @min_seed_id+27);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 228, @min_seed_id+28);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 229, @min_seed_id+29);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 230, @min_seed_id+30);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 231, @min_seed_id+31);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 232, @min_seed_id+32);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 233, @min_seed_id+33);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 234, @min_seed_id+34);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 235, @min_seed_id+35);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 236, @min_seed_id+36);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 237, @min_seed_id+37);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 238, @min_seed_id+38);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 239, @min_seed_id+39);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 240, @min_seed_id+40);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 241, @min_seed_id+41);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 242, @min_seed_id+42);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 243, @min_seed_id+43);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 244, @min_seed_id+44);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 245, @min_seed_id+45);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 246, @min_seed_id+46);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 247, @min_seed_id+47);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 248, @min_seed_id+48);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 249, @min_seed_id+49);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 250, @min_seed_id+50);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 251, @min_seed_id+51);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 252, @min_seed_id+52);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 253, @min_seed_id+53);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 254, @min_seed_id+54);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 255, @min_seed_id+55);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 256, @min_seed_id+56);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 257, @min_seed_id+57);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 258, @min_seed_id+58);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 259, @min_seed_id+59);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 260, @min_seed_id+60);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 261, @min_seed_id+61);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 262, @min_seed_id+62);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 263, @min_seed_id+63);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 264, @min_seed_id+64);

INSERT INTO TOURNAMENT (NAME, TOURNAMENT_TYPE_ID)
VALUES ('2005 Men\s NCAA Tournament', @tournament_type_id);

SELECT @tournament_id:=MAX(TOURNAMENT_ID) FROM TOURNAMENT;

INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 37, @min_seed_id+1);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 18, @min_seed_id+2);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 41, @min_seed_id+3);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 6,  @min_seed_id+4);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 56, @min_seed_id+5);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 74, @min_seed_id+6);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 57, @min_seed_id+7);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 35, @min_seed_id+8);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 10, @min_seed_id+9);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 76, @min_seed_id+10);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 9,  @min_seed_id+11);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 72, @min_seed_id+12);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 73, @min_seed_id+13);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 75, @min_seed_id+14);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 77, @min_seed_id+15);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 71, @min_seed_id+16);

INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 8,  @min_seed_id+17);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 20, @min_seed_id+18);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 2,  @min_seed_id+19);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 42, @min_seed_id+20);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 3,  @min_seed_id+21);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 24, @min_seed_id+22);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 81, @min_seed_id+23);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 12, @min_seed_id+24);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 19, @min_seed_id+25);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 82, @min_seed_id+26);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 79, @min_seed_id+27);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 78, @min_seed_id+28);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 62, @min_seed_id+29);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 80, @min_seed_id+30);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 83, @min_seed_id+31);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 99, @min_seed_id+32);

INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 38, @min_seed_id+33);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 50, @min_seed_id+34);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 4,  @min_seed_id+35);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 21, @min_seed_id+36);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 87, @min_seed_id+37);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 22, @min_seed_id+38);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 25, @min_seed_id+39);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 86, @min_seed_id+40);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 100, @min_seed_id+41);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 51, @min_seed_id+42);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 14, @min_seed_id+43);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 88, @min_seed_id+44);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 89, @min_seed_id+45);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 90, @min_seed_id+46);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 30, @min_seed_id+47);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 85, @min_seed_id+48);

INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 33, @min_seed_id+49);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 1,  @min_seed_id+50);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 95, @min_seed_id+51);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 53, @min_seed_id+52);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 92, @min_seed_id+53);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 11, @min_seed_id+54);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 36, @min_seed_id+55);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 49, @min_seed_id+56);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 34, @min_seed_id+57);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 97, @min_seed_id+58);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 94, @min_seed_id+59);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 93, @min_seed_id+60);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 63, @min_seed_id+61);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 96, @min_seed_id+62);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 98, @min_seed_id+63);
INSERT INTO TOURNAMENT_SEED (TOURNAMENT_ID, TEAM_ID, SEED_ID) VALUES (@tournament_id, 91, @min_seed_id+64);
