SELECT G.*, W.PARENT_GROUP_ID AS PROGENITOR_GROUP_ID
FROM GROUP_NAME G JOIN (
    SELECT COALESCE(PARENT.PARENT_GROUP_ID, CHILD.PARENT_GROUP_ID) AS PARENT_GROUP_ID, CHILD.GROUP_ID
    FROM (
        SELECT COALESCE(PARENT.PARENT_GROUP_ID, CHILD.PARENT_GROUP_ID) AS PARENT_GROUP_ID, CHILD.GROUP_ID
        FROM (
            SELECT COALESCE(CHILD.PARENT_GROUP_ID, CHILD.GROUP_ID) AS PARENT_GROUP_ID, CHILD.GROUP_ID
            FROM GROUP_NAME CHILD
        ) CHILD 
        JOIN GROUP_NAME PARENT ON PARENT.GROUP_ID = CHILD.PARENT_GROUP_ID
    ) CHILD 
    JOIN GROUP_NAME PARENT ON PARENT.GROUP_ID = CHILD.PARENT_GROUP_ID
) W ON G.GROUP_ID = W.GROUP_ID;